/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        tertiary: '#003623',
        'inverse-on-surface': '#f0f1f2',
        'tertiary-fixed-dim': '#4edea3',
        'surface-container-high': '#e7e8e9',
        'surface-bright': '#f8f9fa',
        'primary-fixed-dim': '#95d3ba',
        'on-secondary': '#ffffff',
        surface: '#f8f9fa',
        background: '#f8f9fa',
        'primary-container': '#064e3b',
        'on-tertiary-container': '#31c98f',
        'surface-container-low': '#f3f4f5',
        'secondary-fixed': '#ffdcc3',
        'on-tertiary-fixed-variant': '#005236',
        'surface-dim': '#d9dadb',
        'on-surface-variant': '#404944',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#002117',
        'on-primary-container': '#80bea6',
        error: '#ba1a1a',
        'on-secondary-container': '#663500',
        'tertiary-fixed': '#6ffbbe',
        'on-secondary-fixed-variant': '#6e3900',
        'surface-container': '#edeeef',
        'secondary-container': '#fe932c',
        'on-surface': '#191c1d',
        'primary-fixed': '#b0f0d6',
        'on-error-container': '#93000a',
        'tertiary-container': '#004f34',
        'surface-variant': '#e1e3e4',
        'surface-tint': '#2b6954',
        'inverse-surface': '#2e3132',
        'error-container': '#ffdad6',
        primary: '#003527',
        secondary: '#904d00',
        'outline-variant': '#bfc9c3',
        'on-secondary-fixed': '#2f1500',
        'secondary-fixed-dim': '#ffb77d',
        'on-primary': '#ffffff',
        outline: '#707974',
        'inverse-primary': '#95d3ba',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#002113',
        'on-background': '#191c1d',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#0b513d',
        'surface-container-highest': '#e1e3e4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '48px',
        base: '8px',
        'margin-mobile': '16px',
        gutter: '24px',
        'stack-md': '24px',
        'container-max': '1280px',
        'stack-sm': '12px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Lexend', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Lexend', 'sans-serif'],
        'headline-lg-mobile': ['Lexend', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'title-md': ['Lexend', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}